# Memory sizes
INSTRUCTION_MEMORY_SIZE = 1024
DATA_MEMORY_SIZE = 1024

# Memory addresses
DATA_MEMORY_START_ADDRESS = 0
KEYBOARD_ADDRESS = DATA_MEMORY_SIZE - 2
SCREEN_ADDRESS = DATA_MEMORY_SIZE - 256
END_SCREEN_ADDRESS = KEYBOARD_ADDRESS - 2
STACK_ADDRESS = SCREEN_ADDRESS - 100

# Screen dimensions
SCREEN_WIDTH = 80
SCREEN_HEIGHT = 25